
export const SYLLABUS = [
    {
        id: 'p1',
        code: 'Paper 1',
        name: 'Financial Reporting (FR)',
        shortName: 'FR',
        color: 'text-blue-600 dark:text-blue-400',
        bgColor: 'bg-blue-600',
        bgSoft: 'bg-blue-50 dark:bg-blue-900/20',
        chapters: [
            "Introduction to Indian Accounting Standards",
            "Conceptual Framework for Financial Reporting",
            "Ind AS 1: Presentation of Financial Statements",
            "Ind AS 34: Interim Financial Reporting",
            "Ind AS 7: Statement of Cash Flows",
            "Ind AS 8: Accounting Policies, Changes in Estimates & Errors",
            "Ind AS 10: Events after Reporting Period",
            "Ind AS 113: Fair Value Measurement",
            "Ind AS 2: Inventories",
            "Ind AS 16: Property, Plant and Equipment",
            "Ind AS 23: Borrowing Costs",
            "Ind AS 36: Impairment of Assets",
            "Ind AS 38: Intangible Assets",
            "Ind AS 40: Investment Property",
            "Ind AS 105: Non-current Assets Held for Sale",
            "Ind AS 116: Leases",
            "Ind AS 19: Employee Benefits",
            "Ind AS 37: Provisions, Contingent Liabilities & Assets",
            "Ind AS 12: Income Taxes",
            "Ind AS 21: Effects of Changes in Foreign Exchange Rates",
            "Ind AS 24: Related Party Disclosures",
            "Ind AS 33: Earnings per Share",
            "Ind AS 108: Operating Segments",
            "Ind AS 115: Revenue from Contracts with Customers",
            "Ind AS 41: Agriculture",
            "Ind AS 20: Government Grants",
            "Ind AS 102: Share Based Payment",
            "Ind AS 109/32/107: Financial Instruments",
            "Ind AS 103: Business Combinations",
            "Consolidated Financial Statements (Ind AS 110, 111, 28, 27)",
            "Ind AS 101: First-time Adoption of Ind AS",
            "Analysis of Financial Statements",
            "Professional and Ethical Duty of a CA",
            "Accounting and Technology"
        ]
    },
    {
        id: 'p2',
        code: 'Paper 2',
        name: 'Advanced Financial Management (AFM)',
        shortName: 'AFM',
        color: 'text-emerald-600 dark:text-emerald-400',
        bgColor: 'bg-emerald-600',
        bgSoft: 'bg-emerald-50 dark:bg-emerald-900/20',
        chapters: [
            "Financial Policy and Corporate Strategy",
            "Risk Management",
            "Advanced Capital Budgeting Decisions",
            "Security Analysis",
            "Security Valuation",
            "Portfolio Management",
            "Securitization",
            "Mutual Funds",
            "Derivatives Analysis and Valuation",
            "Foreign Exchange Exposure and Risk Management",
            "International Financial Management",
            "Interest Rate Risk Management",
            "Business Valuation",
            "Mergers, Acquisitions and Corporate Restructuring",
            "Startup Finance"
        ]
    },
    {
        id: 'p3',
        code: 'Paper 3',
        name: 'Advanced Auditing, Assurance & Ethics',
        shortName: 'Audit',
        color: 'text-purple-600 dark:text-purple-400',
        bgColor: 'bg-purple-600',
        bgSoft: 'bg-purple-50 dark:bg-purple-900/20',
        chapters: [
            "Quality Control (SQC 1)",
            "General Auditing Principles & Responsibilities (SA 200 Series)",
            "Audit Planning, Strategy and Execution (SA 300 Series)",
            "Materiality, Risk Assessment & Internal Control",
            "Audit Evidence (SA 500 Series)",
            "Completion and Review (SA 560, 570, 580)",
            "Reporting (SA 700 Series)",
            "Specialised Areas (SA 800 Series)",
            "Audit-related Services (SRS)",
            "Review of Financial Information (SRE)",
            "Prospective Financial Information (SAE)",
            "Digital Auditing and Assurance",
            "Group Audits (SA 600)",
            "Audit of Banks & NBFCs",
            "Audit of Public Sector Undertakings",
            "Internal Audit",
            "Due Diligence, Investigation & Forensic Accounting",
            "SDG & ESG Assurance",
            "Professional Ethics & Liabilities of Auditors"
        ]
    },
    {
        id: 'p4',
        code: 'Paper 4',
        name: 'Direct Tax Laws & International Taxation',
        shortName: 'DT',
        color: 'text-orange-600 dark:text-orange-400',
        bgColor: 'bg-orange-600',
        bgSoft: 'bg-orange-50 dark:bg-orange-900/20',
        chapters: [
            "Basic Concepts & Rates of Tax",
            "Incomes not forming part of Total Income",
            "Profits and Gains of Business or Profession (PGBP)",
            "Capital Gains",
            "Income from Other Sources",
            "Income of Other Persons Included in Assessee's Income",
            "Aggregation of Income, Set Off & Carry Forward",
            "Deductions from Gross Total Income",
            "Assessment of Various Entities (Firms, LLP, AOP, BOI)",
            "Assessment of Trusts, Political Parties & Institutions",
            "Tax Planning, Avoidance and Evasion",
            "Taxation of Digital Transactions",
            "Deduction, Collection and Recovery of Tax (TDS/TCS)",
            "Income Tax Authorities & Assessment Procedure",
            "Appeals, Revision & Dispute Resolution",
            "Miscellaneous Provisions",
            "Provisions to Counteract Unethical Tax Practices",
            "Tax Audit and Ethical Compliances",
            "Non Resident Taxation",
            "Double Taxation Relief (DTAA)",
            "Advance Rulings",
            "Transfer Pricing",
            "Fundamentals of BEPS",
            "Application and Interpretation of Tax Treaties",
            "Overview of Model Tax Conventions",
            "Latest Developments in International Taxation"
        ]
    },
    {
        id: 'p5',
        code: 'Paper 5',
        name: 'Indirect Tax Laws (IDT)',
        shortName: 'IDT',
        color: 'text-teal-600 dark:text-teal-400',
        bgColor: 'bg-teal-600',
        bgSoft: 'bg-teal-50 dark:bg-teal-900/20',
        chapters: [
            "GST: Supply",
            "GST: Charge of GST",
            "GST: Place of Supply",
            "GST: Exemptions",
            "GST: Time of Supply",
            "GST: Value of Supply",
            "GST: Input Tax Credit",
            "GST: Registration",
            "GST: Tax Invoice, Credit and Debit Notes",
            "GST: Accounts and Records; E-way Bill",
            "GST: Payment of Tax",
            "GST: Electronic Commerce Transactions",
            "GST: Returns",
            "GST: Import and Export",
            "GST: Refunds",
            "GST: Job Work",
            "GST: Assessment and Audit",
            "GST: Inspection, Search, Seizure and Arrest",
            "GST: Demands and Recovery",
            "GST: Liability to Pay in Certain Cases",
            "GST: Offences, Penalties & Ethical Aspects",
            "GST: Appeals and Revision",
            "GST: Advance Ruling",
            "GST: Miscellaneous Provisions",
            "Customs: Levy and Exemptions",
            "Customs: Types of Duty",
            "Customs: Classification of Goods",
            "Customs: Valuation",
            "Customs: Importation and Exportation Procedures",
            "Customs: Warehousing",
            "Customs: Refund",
            "Customs: Foreign Trade Policy (FTP)"
        ]
    },
    {
        id: 'p6',
        code: 'Paper 6',
        name: 'Integrated Business Solutions (IBS)',
        shortName: 'IBS',
        color: 'text-rose-600 dark:text-rose-400',
        bgColor: 'bg-rose-600',
        bgSoft: 'bg-rose-50 dark:bg-rose-900/20',
        description: "Multidisciplinary Case Study (Open Book)",
        chapters: [
            "Financial Reporting & Audit Integration",
            "Financial Management & Structuring",
            "Direct & Indirect Tax Implications",
            "Corporate & Economic Laws (IBC, PMLA, FEMA, etc.)",
            "Strategic Management Frameworks",
            "Risk Management & Governance",
            "Case Studies: ICAI Series 1-5",
            "Case Studies: ICAI Series 6-10",
            "Case Studies: Past Papers & RTPs",
            "Case Studies: Mock Test Papers"
        ]
    }
];

export const STATUS_STATES: Record<string, { value: number; label: string; color: string }> = {
    NOT_STARTED: {
        value: 0,
        label: 'Not Started',
        color: 'bg-zinc-100 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400 border-zinc-200 dark:border-zinc-700'
    },
    IN_PROGRESS: {
        value: 1,
        label: 'In Progress',
        color: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400 border-amber-200 dark:border-amber-800'
    },
    REV_1: {
        value: 2,
        label: 'Revision 1',
        color: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400 border-blue-200 dark:border-blue-800'
    },
    REV_2: {
        value: 3,
        label: 'Revision 2',
        color: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400 border-indigo-200 dark:border-indigo-800'
    },
    COMPLETED: {
        value: 4,
        label: 'Completed',
        color: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800'
    },
};
